name: Code Quality

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install jasmine
      - run: npx jasmine init
      - run: tree spec
  markdown_lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown Lint
        uses: articulate/actions-markdownlint@v1.1.0
        with:
          files: '**/*.md'
